package licencly

import (
	"crypto/ed25519"
	"encoding/base64"
	"encoding/json"
	"os"
	"testing"
	"time"
)

// The conformance suite. Every Licencly SDK runs this same file, which is what
// keeps four independent implementations from drifting apart: a vendor
// switching from Python to C# must get identical answers.
//
// testdata/vectors.json is generated by the server repo. Do not edit it here.

type vector struct {
	Name              string            `json:"name"`
	Description       string            `json:"description"`
	File              string            `json:"file"`
	PublicKeys        map[string]string `json:"public_keys"`
	Fingerprint       string            `json:"fingerprint"`
	NowUnix           int64             `json:"now"`
	Expect            string            `json:"expect"`
	NeedsRevalidation bool              `json:"needs_revalidation"`
	MaintenanceActive bool              `json:"maintenance_active"`
}

func loadVectors(t *testing.T) []vector {
	t.Helper()

	raw, err := os.ReadFile("testdata/vectors.json")
	if err != nil {
		t.Fatalf("read vectors: %v", err)
	}

	var doc struct {
		Vectors []vector `json:"vectors"`
	}
	if err := json.Unmarshal(raw, &doc); err != nil {
		t.Fatalf("parse vectors: %v", err)
	}
	if len(doc.Vectors) == 0 {
		t.Fatal("vectors.json is empty")
	}
	return doc.Vectors
}

func keysFor(t *testing.T, v vector) map[string]ed25519.PublicKey {
	t.Helper()

	out := map[string]ed25519.PublicKey{}
	for kid, encoded := range v.PublicKeys {
		raw, err := base64.StdEncoding.DecodeString(encoded)
		if err != nil {
			t.Fatalf("decode key %s: %v", kid, err)
		}
		out[kid] = ed25519.PublicKey(raw)
	}
	return out
}

func TestConformance(t *testing.T) {
	for _, v := range loadVectors(t) {
		t.Run(v.Name, func(t *testing.T) {
			now := time.Unix(v.NowUnix, 0).UTC()

			claims, err := VerifyWithKeys(v.File, keysFor(t, v))
			decision := evaluate(claims, err, now, v.Fingerprint, false)

			if string(decision.Outcome) != v.Expect {
				t.Fatalf("outcome %q, want %q\n  %s", decision.Outcome, v.Expect, v.Description)
			}

			if v.Expect != "valid" {
				return
			}
			if decision.NeedsRevalidation != v.NeedsRevalidation {
				t.Errorf("needs_revalidation = %v, want %v", decision.NeedsRevalidation, v.NeedsRevalidation)
			}
			if got := decision.MaintenanceActive(now); got != v.MaintenanceActive {
				t.Errorf("maintenance_active = %v, want %v", got, v.MaintenanceActive)
			}
		})
	}
}

// Tampering must never be reported as something worth retrying: a client that
// retries a forged file hides an attack behind what looks like a flaky network.
func TestTamperingIsNotRetryable(t *testing.T) {
	for _, v := range loadVectors(t) {
		if v.Expect != "invalid" {
			continue
		}
		t.Run(v.Name, func(t *testing.T) {
			_, err := VerifyWithKeys(v.File, keysFor(t, v))
			if err == nil {
				t.Fatal("a vector expecting invalid verified successfully")
			}
			if IsNetwork(err) {
				t.Fatal("verification failure reported as a network error")
			}
			if !IsTampering(err) {
				t.Fatalf("IsTampering false for %v: callers will treat this as retryable", err)
			}
		})
	}
}

// The suite is only worth running if it covers the failure modes.
func TestVectorsCoverEveryOutcome(t *testing.T) {
	seen := map[string]bool{}
	for _, v := range loadVectors(t) {
		seen[v.Expect] = true
	}

	for _, outcome := range []string{"valid", "invalid", "not_active", "expired", "wrong_machine", "stale"} {
		if !seen[outcome] {
			t.Errorf("no vector expects %q", outcome)
		}
	}
}
